### PR TITLE
Replace temp-table scope with CTE scope, add recall operator test

### PR DESCRIPTION
**Pull request by jeremyevans**
This replaces temp-table use with CTE use.  This has the advantage
of ripping out all of the code related to prepping queries.

This also adds a test for the recall operator.  With the previous
code, the recall operator test failed, both for the union part
and the except part.

This implementation isn't perfect, mostly to work around the fact
that operators run queries to get columns.  If we can fix things
so that operators always know the columns or can figure them out
without database queries, that will fix the main issue with this
implementation.

Unlike most of the other pull requests, I think this one needs to
be considered carefully before being merged.  It does appear to
fix the issues with the temp table implementation, but I'm not
sure if it performs worse on large datasets.

### CODE REVIEW

**Comment by aguynamedryan** [comment]
Naively, the columns created by a call to Operator#evaluate should always be the same set of columns that ConceptQL uses as the intermediate representation of all results.

I don't recall off-hand why we're always checking for columns.  Most likely it's done so that when a selection operator is pulling out data from the tables, it can detect which columns in the intermediate representation aren't satisfied by the table and so the operator will insert NULL in those columns.

**Comment by jeremyevans** [comment]
It may be possible to eliminate the queries to get the columns, by making operators keep track of the columns they are using, so they don't need to ask the dataset for them.  I'm not sure how difficult it would be to make that change internally.  If you'd like me to investigate it, please let me know.

**Comment by aguynamedryan** [comment]
I just want to jot down some thoughts, though I'm not sure there's anything actionable in here:

The Operator class currently handles keeping track of the columns for all subclasses.  It's the one issuing calls to Dataset#columns and also tracking columns for specific tables.

I think it would definitely behoove us to move this logic out of Operator and transfer the responsibility to each subclass of Operator.  As it stands, some of the logic in Operator is tied specifically to CDMv4, and it would be much better if each subclass defined this logic, especially since #21 introduces multiple data models.

By default, I think virtually all mutator operators should be able to expect that they are manipulating the same set of columns.

It is only the selection operators that must determine which columns in a particular table are mapped to certain columns in the intermediate representation.

Each selection operator might interact with more than one table, e.g. the Icd9 Operator might pull some ICD-9s from the `condition_occurrence` table and some ICD-9s from the `procedure_occurrence` table.

I wonder if we can provide a default mapping for the columns of each table into the intermediate representation of ConceptQL, then, when necessary, override that default mapping on an operator-by-operator basis.

A selection operator might need to run a pre-check query to determine what tables it will need to pull results from.  Then, for each table, it will need to convert the rows of that table into intermediate results.  Other selection operators might be guaranteed to always pull from a specific set of tables.

Either way, it seems that tables should track how they are turned into intermediate results and each operator can determine the tables they need to map to results and, if necessary (though I don't have a use case off the top of my head) an operator can override how certain columns are mapped into results.

**Comment by jeremyevans** [comment]
I've rebased the previous commit against the develop branch, and added a new commit which skips all the queries to retrieve the columns.   This improves performance in the test suite by about 50% on PostgreSQL, and I would guess the speedup on Impala is significantly more.

**Pull request merged**
